### ISSUE TITLE
Blog Hero Image doesn't stay in container

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-website#146]
![image](https://user-images.githubusercontent.com/772569/71187536-e0089200-2244-11ea-85bd-3a933e527ab8.png)

**Comment by csell5** [comment]
since I am on a widescreen I see it stretch out, but the standard size media queries seem to work. it should just fall in line with the rest of the text.

**Comment by tsidel** [comment]
I think the issue is that the image width is defined by vw which takes its width based on the browser window. So as you make the browser bigger, the image will always be 62% of the browser width (as defined by width:62vw.)  The ContentSection container has a max-width of 140rem on it.  You could change the inline style to width:100% then it will always be as wide as the 140rem ContentSection block. 

But you'll also run into the issue on other images in this blog post like Grace Hopper photo. Its width is 35vw, so it'll always be 35% of the browser width, eventually being wider than the ContentSection block, if your screen is big enough.

I'm not sure what the styling choices/decisions were for vw vs rems vs %s. So I'm not sure quite the best way to fix this.. but I think I've been able to diagnose the issue.
