### ISSUE TITLE
Submit session button on Session preview page not working

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#229]
## Issue
After submitting a session you are brought to a "Preview" page for that session. On this page is a **Session Submit** button. Using this button results in an error.

## Steps to reproduce
1. Create a new session
1. When on the **Preview** page, `/wi/session/submit/preview` Click off the page, wait 30 seconds.
    1. you'll notice that the site will dispose the pages (server console):
    1. `[ event ] disposing inactive page(s): /member/my-sessions, /wi/session/submit/details, /wi/call-for-counselors, /wi/counselor-start, /wi/counselor-agreement, /wi/session/submit`
1. click the button "Submit Session" 

### What happens
The site navigates to "my sessions" (member/my-sessions) briefly the displays an error. 
If the "Submit Session" button is used right away, right after sessions submission, the error doesn't occur. 

After waiting for a bit, filing out this issue, the page refreshed and loaded the sessions as expected.

### What should happen
Navigate cleanly to My Sessions page. 

### Additional information
Error: Rendered more hooks than during the previous render.
▶ 6 stack frames were collapsed.
CurrentSessions
./components/Member/MySessions/Current.js:100
   97 |   }
   98 | `;
   99 | 
> 100 | const CurrentSessions = ({ dispatch }) => {
  101 |   const { loading, error, data } = useQuery(GET_MY_SESSIONS, {
  102 |     variables: {},
  103 |   });
View compiled
▶ 39 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

![image](https://user-images.githubusercontent.com/473633/71910831-42fc9300-3138-11ea-80dc-e38285473828.png)

**Comment by mcookWI** [comment]
It also looks like the sessions that are hanging are getting written somewhere - when I was able to get to the My Sessions page in Firefox (only browser I am able to at this point), I am seeing all of these additional sessions out there with incorrect titles. When I go to edit any of those "Temporary" ones, there is nothing in them except for the title:

<img width="1037" alt="Screen Shot 2020-01-07 at 7 25 34 PM" src="https://user-images.githubusercontent.com/5367626/71943333-efb13180-3185-11ea-93f4-e8b44d49d161.png">

**Comment by saragibby** [comment]
@brettski @mcookWI I believe the errors on this page have been fixed. The additional sessions listed, the temporary ones, is more of an usability issue we should think through. Those are ones that were abandoned during submission or was an error.

**Comment by mcookWI** [comment]
Sessions are no longer hanging upon final submission. However, other items to note:

1. When a new session is created, but abandoned on the very first page, we end up with a "Step1_Temporary_Title" session in 'Draft' status. (see below)
2. If the user gets to at least the second page of the submission process and abandons, the session shows up in their listing with the Title they entered. (see below)

If a user abandons their session submission before continuing to page 2, we may want to consider deleting the request. Otherwise, the "Step1_Temporary_Title" session in their listing may cause confusion.

<img width="1007" alt="Screen Shot 2020-01-13 at 3 20 06 PM" src="https://user-images.githubusercontent.com/5367626/72293283-d2161900-3618-11ea-8c72-05e936f19818.png">

**Comment by brettski** [comment]
Corrected
