### ISSUE TITLE
https://www.thatconference.com/foo "Yes, Take me now!" button redirects to another 'Page Not Found' on old site

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#55]
The https://www.thatconference.com/foo "Yes, Take me now!" button redirects to another 'Page Not Found' on old site - https://old.thatconference.com/foo 

<img width="830" alt="Screen Shot 2019-10-27 at 5 32 25 PM" src="https://user-images.githubusercontent.com/5367626/67643009-10385200-f8e0-11e9-9029-8dcc98362b0f.png">

**Comment by saragibby** [comment]
@csell5 I got this fixed as part of #57

**Comment by mcookWI** [comment]
"Yes, Take me now!" button is still redirecting to the old 404 page.

**Comment by csell5** [comment]
A larger conversation we should have. It’s happening because we don’t really know what site that request was meant for. So I just assumed if we didn’t have it, then send you to the old site. 

Now having said that, this morning I added the notion of an event to our url so I might be able to be smarter about it. 

It’s also a bit of a timing thing, once we get the content ported, then this goes away too as we won’t redirect. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saragibby** [comment]
@csell5 sounds like we still have a to do here to fix this? Or is this just a known dealio until the site is built out and old data is ported over?

**Comment by csell5** [comment]
it's broken now.. it will be naturally fixed. I'd rather just fix it right and not spend energy on bandaids.

**Comment by mcookWI** [comment]
Corrected with #344
