### ISSUE TITLE
/wi has two newsletter signup boxes

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#65]
thatconference.com/wi contains two newsletter signup boxes. The "Join our Mailing List" button in the header takes the user to the one in the page footer. Can the signup box 2/3 of the way down be removed?

<img width="469" alt="Screen Shot 2019-10-30 at 8 44 30 PM" src="https://user-images.githubusercontent.com/5367626/67912314-8abed700-fb57-11e9-8074-44e75a70b212.png">
<img width="962" alt="Screen Shot 2019-10-30 at 8 44 06 PM" src="https://user-images.githubusercontent.com/5367626/67912322-8f838b00-fb57-11e9-85c1-9d9081785032.png">

**Comment by saragibby** [comment]
That was by design. On the previous site the newsletter sign up was somewhat buried and we wanted to be sure to give it attention on the new site. Once the footer is filled in with the navigation and the footer newsletter sign up the duplication won't be as noticeable.

Also, I have a feeling we may use this section for other "call to action" items as we come fully alive.
